#define SSID "XXXXXX"
#define PASSWORD "XXXXXXXXX"

#define MQTT_USERNAME "OKUL_PROJE"
#define MQTT_PASSWORD "8W4C432G2FMI2LAI"
#define MQTT_WRITE_API_KEY  "S6QXUQJ465B22EC4"
#define MQTT_READ_API_KEY  "KKPUWCS18TDFYV2W"
#define MQTT_CHANNEL_ID 1034607
#define MQTT_PUB_FIELD_LIGHT 1
#define MQTT_SUB_FIELD_MOBILE_LEVEL 2 
#define MQTT_SUB_FIELD_MOBILE_MODE 3 
#define MQTT_SERVER "mqtt.thingspeak.com"